Add a check for architecture availability.

diff --git a/Dockerfile.template b/Dockerfile.template
--- a/Dockerfile.template
+++ b/Dockerfile.template
@@ -26,6 +26,9 @@ RUN set -eux; \
     arm64) url='%%URL_ARM64%%'; sha256='%%SHA_ARM64%%' ;; \
     *) echo >&2 "error: unsupported architecture: ${dpkgArch}"; exit 1 ;; \
   esac; \
+  if [ "$url" = "none" ]; then \
+    echo >&2 "error: no upstream binary for ${dpkgArch} in this Nim version"; exit 1; \
+  fi; \
   curl --fail --location "$url" --output nim.tar.xz; \
   echo "$sha256 *nim.tar.xz" | sha256sum --check --strict -; \
   mkdir -p /opt/nim; \
diff --git a/dockerfiles/2.2.6/Dockerfile b/dockerfiles/2.2.6/Dockerfile
--- a/dockerfiles/2.2.6/Dockerfile
+++ b/dockerfiles/2.2.6/Dockerfile
@@ -23,9 +23,12 @@ RUN set -eux; \
   dpkgArch="$(dpkg --print-architecture)"; \
   case "${dpkgArch}" in \
     amd64) url='https://github.com/nim-lang/nightlies/releases/download/2025-10-31-version-2-2-ab00c56904e3126ad826bb520d243513a139436a/nim-2.2.6-linux_x64.tar.xz'; sha256='38b8407f87d78bd207390051e4c76f38a45d0a26983cb262017c899b56ad8d06' ;; \
-    arm64) url='none'; sha256='0' ;; \
+    arm64) url='none'; sha256='none' ;; \
     *) echo >&2 "error: unsupported architecture: ${dpkgArch}"; exit 1 ;; \
   esac; \
+  if [ "$url" = "none" ]; then \
+    echo >&2 "error: no upstream binary for ${dpkgArch} in this Nim version"; exit 1; \
+  fi; \
   curl --fail --location "$url" --output nim.tar.xz; \
   echo "$sha256 *nim.tar.xz" | sha256sum --check --strict -; \
   mkdir -p /opt/nim; \
