Regen images: update base and sha.

diff --git a/dockerfiles/2.0.4/Dockerfile b/dockerfiles/2.0.4/Dockerfile
--- a/dockerfiles/2.0.4/Dockerfile
+++ b/dockerfiles/2.0.4/Dockerfile
@@ -1,4 +1,4 @@
-FROM node:lts-trixie
+FROM debian:trixie-slim
 
 RUN set -eux; \
   apt-get update; \
@@ -12,7 +12,9 @@ RUN set -eux; \
     curl \
     xz-utils \
   ; \
-  apt-get dist-clean
+  apt-get autoremove -y; \
+  apt-get clean; \
+  rm -rf /var/lib/apt/lists/*
 
 ENV NIM_VERSION=2.0.4
 ENV PATH="/opt/nim/bin:${PATH}"
@@ -24,8 +26,13 @@ RUN set -eux; \
   case "${dpkgArch}" in \
     amd64) url='https://github.com/nim-lang/nightlies/releases/download/2024-03-28-version-2-0-b47747d31844c6bd9af4322efe55e24fefea544c/nim-2.0.4-linux_x64.tar.xz'; sha256='2ca6e7b701bdfee2e7a8def2f0f5eeba026420c612261faa3d4a85be04c679b5' ;; \
     arm64) url='https://github.com/nim-lang/nightlies/releases/download/2024-03-28-version-2-0-b47747d31844c6bd9af4322efe55e24fefea544c/nim-2.0.4-linux_arm64.tar.xz'; sha256='a907adc2ef294d632969877438a5643ffad7b03995d947381b01630fe444f3a4' ;; \
+    i386)  url='https://github.com/nim-lang/nightlies/releases/download/2024-03-28-version-2-0-b47747d31844c6bd9af4322efe55e24fefea544c/nim-2.0.4-linux_x32.tar.xz';  sha256='50a67191af157ee860f600e33f333895a92faa956ed27b7fb99a167e20a77b7f' ;; \
+    armhf) url='https://github.com/nim-lang/nightlies/releases/download/2024-03-28-version-2-0-b47747d31844c6bd9af4322efe55e24fefea544c/nim-2.0.4-linux_armv7l.tar.xz'; sha256='fda40d94e88859fcd66892a3780d8b4ef818e795074aae331be187c88ffbb4f9' ;; \
     *) echo >&2 "error: unsupported architecture: ${dpkgArch}"; exit 1 ;; \
   esac; \
+  if [ "$url" = "none" ]; then \
+    echo >&2 "error: no upstream binary for ${dpkgArch} in this Nim version"; exit 1; \
+  fi; \
   curl --fail --location "$url" --output nim.tar.xz; \
   echo "$sha256 *nim.tar.xz" | sha256sum --check --strict -; \
   mkdir -p /opt/nim; \
