Update Dockerfiles.

diff --git a/dockerfiles/2.0.12/Dockerfile b/dockerfiles/2.0.12/Dockerfile
--- a/dockerfiles/2.0.12/Dockerfile
+++ b/dockerfiles/2.0.12/Dockerfile
@@ -1,4 +1,4 @@
-FROM node:lts-trixie
+FROM debian:trixie-slim
 
 RUN set -eux; \
   apt-get update; \
@@ -12,7 +12,9 @@ RUN set -eux; \
     curl \
     xz-utils \
   ; \
-  apt-get dist-clean
+  apt-get autoremove -y; \
+  apt-get clean; \
+  rm -rf /var/lib/apt/lists/*
 
 ENV NIM_VERSION=2.0.12
 ENV PATH="/opt/nim/bin:${PATH}"
@@ -24,8 +26,13 @@ RUN set -eux; \
   case "${dpkgArch}" in \
     amd64) url='https://github.com/nim-lang/nightlies/releases/download/2024-11-01-version-2-0-ce7c6f4f3365db2cc63bdd9d460c71ed937ee9e9/nim-2.0.12-linux_x64.tar.xz'; sha256='b89e0d38f55cd207b0dacb5ee4d6cef4fd1268b63c1490f923d6959839f4548c' ;; \
     arm64) url='https://github.com/nim-lang/nightlies/releases/download/2024-11-01-version-2-0-ce7c6f4f3365db2cc63bdd9d460c71ed937ee9e9/nim-2.0.12-linux_arm64.tar.xz'; sha256='fad4dceef1e208407f94e284dd948fe0732dfe85c999f03dba35c5c64063a0be' ;; \
+    i386)  url='https://github.com/nim-lang/nightlies/releases/download/2024-11-01-version-2-0-ce7c6f4f3365db2cc63bdd9d460c71ed937ee9e9/nim-2.0.12-linux_x32.tar.xz';  sha256='0' ;; \
+    armhf) url='https://github.com/nim-lang/nightlies/releases/download/2024-11-01-version-2-0-ce7c6f4f3365db2cc63bdd9d460c71ed937ee9e9/nim-2.0.12-linux_armv7l.tar.xz'; sha256='0' ;; \
     *) echo >&2 "error: unsupported architecture: ${dpkgArch}"; exit 1 ;; \
   esac; \
+  if [ "$url" = "none" ]; then \
+    echo >&2 "error: no upstream binary for ${dpkgArch} in this Nim version"; exit 1; \
+  fi; \
   curl --fail --location "$url" --output nim.tar.xz; \
   echo "$sha256 *nim.tar.xz" | sha256sum --check --strict -; \
   mkdir -p /opt/nim; \
diff --git a/dockerfiles/2.0.14/Dockerfile b/dockerfiles/2.0.14/Dockerfile
--- a/dockerfiles/2.0.14/Dockerfile
+++ b/dockerfiles/2.0.14/Dockerfile
@@ -1,4 +1,4 @@
-FROM node:lts-trixie
+FROM debian:trixie-slim
 
 RUN set -eux; \
   apt-get update; \
@@ -12,7 +12,9 @@ RUN set -eux; \
     curl \
     xz-utils \
   ; \
-  apt-get dist-clean
+  apt-get autoremove -y; \
+  apt-get clean; \
+  rm -rf /var/lib/apt/lists/*
 
 ENV NIM_VERSION=2.0.14
 ENV PATH="/opt/nim/bin:${PATH}"
@@ -24,8 +26,13 @@ RUN set -eux; \
   case "${dpkgArch}" in \
     amd64) url='https://github.com/nim-lang/nightlies/releases/download/2024-12-23-version-2-0-bf4de6a394e040d9810cba8c69fb2829ff04dcc6/nim-2.0.14-linux_x64.tar.xz'; sha256='ae7ab1178565b8b56848ac714c3be0efa565f32684aca9bea6bd0aab11047ba3' ;; \
     arm64) url='https://github.com/nim-lang/nightlies/releases/download/2024-12-23-version-2-0-bf4de6a394e040d9810cba8c69fb2829ff04dcc6/nim-2.0.14-linux_arm64.tar.xz'; sha256='7f21018b88ac1afc1fd563dc4208e94fa2941ab8bbc873a234f87e19b95a461b' ;; \
+    i386)  url='https://github.com/nim-lang/nightlies/releases/download/2024-12-23-version-2-0-bf4de6a394e040d9810cba8c69fb2829ff04dcc6/nim-2.0.14-linux_x32.tar.xz';  sha256='9e038c760d591f96337f62ca3abf3c739f23d7f9b91ebf6627e52ad5ffc0a4df' ;; \
+    armhf) url='https://github.com/nim-lang/nightlies/releases/download/2024-12-23-version-2-0-bf4de6a394e040d9810cba8c69fb2829ff04dcc6/nim-2.0.14-linux_armv7l.tar.xz'; sha256='c15439e201cd9ecb83a655c7c30b088ae06593de07717571bc77e1fc7b606f28' ;; \
     *) echo >&2 "error: unsupported architecture: ${dpkgArch}"; exit 1 ;; \
   esac; \
+  if [ "$url" = "none" ]; then \
+    echo >&2 "error: no upstream binary for ${dpkgArch} in this Nim version"; exit 1; \
+  fi; \
   curl --fail --location "$url" --output nim.tar.xz; \
   echo "$sha256 *nim.tar.xz" | sha256sum --check --strict -; \
   mkdir -p /opt/nim; \
diff --git a/dockerfiles/2.0.8/Dockerfile b/dockerfiles/2.0.8/Dockerfile
--- a/dockerfiles/2.0.8/Dockerfile
+++ b/dockerfiles/2.0.8/Dockerfile
@@ -1,4 +1,4 @@
-FROM node:lts-trixie
+FROM debian:trixie-slim
 
 RUN set -eux; \
   apt-get update; \
@@ -12,7 +12,9 @@ RUN set -eux; \
     curl \
     xz-utils \
   ; \
-  apt-get dist-clean
+  apt-get autoremove -y; \
+  apt-get clean; \
+  rm -rf /var/lib/apt/lists/*
 
 ENV NIM_VERSION=2.0.8
 ENV PATH="/opt/nim/bin:${PATH}"
@@ -24,8 +26,13 @@ RUN set -eux; \
   case "${dpkgArch}" in \
     amd64) url='https://github.com/nim-lang/nightlies/releases/download/2024-07-03-version-2-0-5935c3bfa9fec6505394867b23510eb5cbab3dbf/nim-2.0.8-linux_x64.tar.xz'; sha256='c971320d391db30917b3b61c471cff4b3cd3cd883d4f7af099d3c9018cc15683' ;; \
     arm64) url='https://github.com/nim-lang/nightlies/releases/download/2024-07-03-version-2-0-5935c3bfa9fec6505394867b23510eb5cbab3dbf/nim-2.0.8-linux_arm64.tar.xz'; sha256='144caecaa5750ba7aca52062322645fe6cb64063074168e0f459653c3a71fa7f' ;; \
+    i386)  url='https://github.com/nim-lang/nightlies/releases/download/2024-07-03-version-2-0-5935c3bfa9fec6505394867b23510eb5cbab3dbf/nim-2.0.8-linux_x32.tar.xz';  sha256='ccb27d7bdedd585c59670f444f6d075bde6844a2f2398652708ddb415c36e4d8' ;; \
+    armhf) url='https://github.com/nim-lang/nightlies/releases/download/2024-07-03-version-2-0-5935c3bfa9fec6505394867b23510eb5cbab3dbf/nim-2.0.8-linux_armv7l.tar.xz'; sha256='6b588dc6f286d2f37f4bc75583b1dc5400377deec4db7fa865915e6f681133e0' ;; \
     *) echo >&2 "error: unsupported architecture: ${dpkgArch}"; exit 1 ;; \
   esac; \
+  if [ "$url" = "none" ]; then \
+    echo >&2 "error: no upstream binary for ${dpkgArch} in this Nim version"; exit 1; \
+  fi; \
   curl --fail --location "$url" --output nim.tar.xz; \
   echo "$sha256 *nim.tar.xz" | sha256sum --check --strict -; \
   mkdir -p /opt/nim; \
