Update Dockerfiles.

diff --git a/dockerfiles/1.6.4/Dockerfile b/dockerfiles/1.6.4/Dockerfile
--- a/dockerfiles/1.6.4/Dockerfile
+++ b/dockerfiles/1.6.4/Dockerfile
@@ -25,7 +25,10 @@ RUN case "${TARGETARCH}" in \
   "arm")   URL=$URL_ARMV7 && CHKSUM=$SHA_ARMV7 ;; \
   *) echo "Unsupported arch: ${TARGETARCH}"; exit 1 ;; \
   esac && \
-  if [ "$URL" = "none" ]; then echo "Binary not found for $TARGETARCH"; fi && \
+  if [ "$URL" = "none" ] || [ -z "$URL" ]; then \
+  echo "Error: Nim binary not available for ${TARGETARCH} in version ${NIM_VERSION}"; \
+  exit 1; \
+  fi && \
   curl -L "$URL" -o nim.tar.xz && \
   echo "${CHKSUM}  nim.tar.xz" | sha256sum -c - && \
   tar -xJf nim.tar.xz && \
@@ -35,4 +38,3 @@ RUN case "${TARGETARCH}" in \
 ENV PATH="/root/.nimble/bin:/opt/nim/bin:${PATH}"
 WORKDIR /usr/src/app
 CMD ["nim", "--help"]
- 
